#!/usr/bin/env bash
if [[ -d "$1" ]]; then
  if [[ -d .git ]]; then

    REV=`git describe --always`
    rm -rf _public
    git clone $(git remote get-url origin) --depth 1 -b gh-pages _public
    cd _public
    git rm -r *
    cp -R ../$1/* ./
    git add *
    git commit -m "regen for $REV"
    git push
    cd ..
    rm -rf _public
  else
    echo "please use deploy under a git repo."
  fi
else
  echo "please specify static folder."
fi
